export const t = {
  primary:                 "#386A20",
  onPrimary:               "#FFFFFF",
  primaryContainer:        "#B8F397",
  onPrimaryContainer:      "#042100",
  secondary:               "#55624C",
  onSecondary:             "#FFFFFF",
  secondaryContainer:      "#D9E7CB",
  onSecondaryContainer:    "#131F0D",
  error:                   "#BA1A1A",
  onError:                 "#FFFFFF",
  errorContainer:          "#FFDAD6",
  onErrorContainer:        "#410002",
  surface:                 "#FDFDF5",
  onSurface:               "#1A1C18",
  onSurfaceVariant:        "#43483E",
  outline:                 "#73796E",
  outlineVariant:          "#C3C8BC",
  surfaceContainerLowest:  "#FFFFFF",
  surfaceContainerLow:     "#F4F6EE",
  surfaceContainer:        "#EEF0E8",
  surfaceContainerHigh:    "#E8EBE3",
  background:              "#F4F6EE",
  elevation1:              "0 1px 2px rgba(0,0,0,.1), 0 1px 3px 1px rgba(0,0,0,.08)",
  elevation3:              "0 4px 8px 3px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.12)",
} as const;
